{{- $currentScope := .}}
{{- $cpath := .Values.configs.path }}
{{- $cnamespace := .Release.Namespace }}
{{- $labels := include "infra.labels" . }}
{{- range $path, $_ :=  .Files.Glob  $cpath }}
{{- $currentName := printf "%s-%s" (base $path | trimSuffix ".toml") ("configmap") }}
{{- if not (lookup "v1" "ConfigMap" $cnamespace $currentName) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $currentName }}
  labels:
    {{- $labels | nindent 4 }}
data:
  {{- with $currentScope}}
    {{ base $path }}: |
    {{- ( .Files.Get $path ) | nindent 8 }}
    {{- end }}
{{- end }}
---
{{- end }}