{{- $currentScope := .}}
{{- $cpath := .Values.configs.path }}
{{- $cnamespace := .Release.Namespace }}
{{- range $path, $_ :=  .Files.Glob  $cpath }}
{{- $currentName := printf "%s-%s" (base $path | trimSuffix ".toml") ("configmap") }}
{{- if not (lookup "v1" "ConfigMap" $cnamespace $currentName) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $currentName }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
data:
  {{- with $currentScope}}
    {{ base $path }}: |
    {{- ( .Files.Get $path ) | nindent 8 }}
    {{- end }}
{{- end }}
---
{{- end }}