{{- if eq .Values.serviceMonitor.enabled true }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-prometheus-monitoring
  labels:
    {{- include "infra.labels" . | nindent 4 }}
    app.kubernetes.io/component: middleware
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  endpoints:
    - port: redis-exporter
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
  namespaceSelector:
    matchNames:
      - {{ .Values.serviceMonitor.namespace | default .Release.Namespace }}
{{- end }}