apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tdengine.fullname" . }}-arbitrator
  labels:
    {{- include "tdengine.labels" . | nindent 4 }}
    app: "arbitrator"
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "tdengine.selectorLabels" . | nindent 6 }}
      app: "arbitrator"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tdengine.selectorLabels" . | nindent 8 }}
        app: "arbitrator"
    spec:
      containers:
      - name: arbitrator
        image: "{{ .Values.image.prefix }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ["tarbitrator"]
        ports:
        - name: tcp6042
          containerPort: 6042
          protocol: TCP

