apiVersion: v1
kind: Service
metadata:
  name: {{ include "tdengine.fullname" . }}-arbitrator
  labels:
    {{- include "tdengine.labels" . | nindent 4 }}
    app: "arbitrator"
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  type: ClusterIP
  ports:
    - name: tcp6042
      port: 6042
      protocol: TCP
  selector:
    app: "arbitrator"
