---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tdengine.fullname" . }}-taoscfg
  labels:
    {{- include "tdengine.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
data:
{{- with .Values.taoscfg }}
  {{- toYaml . | nindent 2 }}
{{- end }}
