apiVersion: v1
kind: Service
metadata:
  name: {{ include "tdengine.fullname" . }}
  labels:
    serviceName: "tdengine"
    {{- include "tdengine.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  type: {{ .Values.service.type }}
  ports: {{ range $idx, $val := .Values.service.ports.tcp }}
    - name: tcp{{- $idx}}
      port: {{ $val }}
      protocol: TCP
    {{- end }}
    {{ range $idx, $val := .Values.service.ports.udp }}
    - name: udp {{- $idx}}
      port: {{ $val }}
      protocol: UDP
    {{- end }}
  selector:
    {{- include "tdengine.selectorLabels" . | nindent 4 }}
    app: "taosd"

